version: '3.3'
services:
  kangaroo:
#    container_name: kangaroo
    build:
        context: ./kangaroo
        dockerfile: Dockerfile
    image: 'img/kangaroo'
    ports:
      - '8090'
    links:
      - arquimedes:arquimedes
      - knowsmore:knowsmore
    depends_on:
      - knowsmore
      - arquimedes
    networks:
      - micro
    environment:
            - "spring.cloud.config.uri=http://knowsmore:8888/"
            - "SPRING_PROFILES_ACTIVE=dev"
            - "WAIT_HOSTS=knowsmore:8888,arquimedes:8761"
            - "WAIT_HOSTS_TIMEOUT=100"

  golden:
    container_name: golden
    image: 'img/golden'
    build:
      context: ./golden
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - knowsmore
      - arquimedes
    links:
      - arquimedes:arquimedes
      - knowsmore:knowsmore
      - kangaroo:kangaroo
    networks:
      - micro
    environment:
            - "spring.cloud.config.uri=http://knowsmore:8888/"
            - "SPRING_PROFILES_ACTIVE=dev"
            - "WAIT_HOSTS=knowsmore:8888,arquimedes:8761"
            - "WAIT_HOSTS_TIMEOUT=100"

  knowsmore: #configuration-server
    container_name: knowsmore
    image: 'img/knowsmore'
    build:
        context: ./knowsmore
        dockerfile: Dockerfile
    ports:
      - '8888:8888'
    links:
      - arquimedes:arquimedes
    networks:
      - micro

  arquimedes: #eureka-server
    container_name: arquimedes
    build:
        context: ./arquimedes
        dockerfile: Dockerfile
    image: 'img/arquimedes'
    ports:
      - '8761:8761'
    networks:
      - micro
    environment:
            - "spring.cloud.config.uri=http://knowsmore:8888/"
            - "SPRING_PROFILES_ACTIVE=default"

  gandalf:  #zuul-api-gateway
    container_name: gandalf
    build:
        context: ./gandalf
        dockerfile: Dockerfile
    image: 'img/gandalf'
    links:
      - arquimedes:arquimedes
      - knowsmore:knowsmore
      - golden:golden
      - kangaroo:kangaroo
    ports:
      - '8181:8181'
    networks:
      - micro
    environment:
            - "spring.cloud.config.uri=http://knowsmore:8888/"
            - "SPRING_PROFILES_ACTIVE=default"
            - "WAIT_HOSTS=knowsmore:8888,arquimedes:8761"
            - "WAIT_HOSTS_TIMEOUT=100"

  ha_kangaroo:
    image: 'tutum/haproxy'
    links:
      - kangaroo
    ports:
      - "8090:8090"

networks:
  micro:
    driver: bridge

